### ISSUE TITLE
Add most recent division to team page

### ISSUE THREAD

**Issue by Fabian-Sommer** [kealsera/rikki#119]
Relevant when divisions are assigned but no matches have been created yet. In that case, the team page should display the most recently created division without matches.

**Comment by kealsera** [comment]
How about showing the new div table component where you are able to see table +- 2 places around a team?

Just saying Team is/was in SX Div X seems a bit tard.

Altho we could just show the matches thing even when no match has been played yes - due to the header being SX - DivX Matches people would know the assigned div.
