### ISSUE TITLE
match replay info request returning improper json

### ISSUE THREAD

**Issue by Takaloy** [kealsera/rikki#30]
it's returning an array instead of a json containing array data.

not really a problem but nice to have it standardised.

example : https://heroeslounge.gg/api/v1/matches/119/replays

**Comment by kealsera** [comment]
@Takaloy It's returning an array, because there are multiple Json Entries being returned? That's proper json

![image](https://user-images.githubusercontent.com/10854875/30074936-96b5bb72-9273-11e7-9b81-390b0418abfc.png)


just like: http://localhost/hl/api/v1/seasons/1/teams

closed until clearyfied

**Comment by Takaloy** [comment]
![image](https://user-images.githubusercontent.com/4484516/31286631-b805471a-aab6-11e7-9b66-b253b4b8151e.png)

it's currently returned as text/html 
the return type should be application/json
